### ISSUE TITLE
Pregunta sobre los estilos

### ISSUE THREAD

**Issue by jlobos** [zkreations/Canvas.xml#2]
No estoy familiarizado con el sistema de plantillas de Blogger, noto que siempre los estilos se incrustan directamente en el archivo, cual seria la diferencia al obtenerlos de una fuente externa, afectaría esto al sistema de plantillas de Blogger? por ejemplo si necesito `normalize.css`:

```html
<head>
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css"
  />
</head>
```

**Comment by zkreations** [comment]
No habria ningun problema amigo. en blogger puedes subir tus estilos mediante archivos externos o incrustarlo directamente en el blog. Yo prefiero incrustarlo porque no tengo donde alojarlos para que sean permanentes, ya que yo comparto diseños que todos pueden usar.


________________________________
De: Jesús Lobos <notifications@github.com>
Enviado: lunes, 10 de julio de 2017 0:20
Para: zkreations/Canvas.xml
Cc: Subscribed
Asunto: [zkreations/Canvas.xml] Pregunta sobre los estilos (#2)


No estoy familiarizado con el sistema de plantillas de Blogger, noto que siempre los estilos se incrustan directamente en el archivo, cual seria la diferencia al obtenerlos de una fuente externa, afectaría esto al sistema de plantillas de Blogger? por ejemplo si necesito normalize.css:
