### ISSUE TITLE
[Request] Restoring the "Relationados" widget + some tips

### ISSUE THREAD

**Issue by Warmuser** [zkreations/Canvas.xml#3]
Please, can you suggest me how to replace the "Top semanal" widget with the older "Relationados" widget like in the previous version? I mean like on Materiald template: https://demo-materiald.blogspot.it/2016/09/material-design.html. 

And I also want to ask you If there is some possible way to have clickable "data__title" with the hidden "card__data". Thanks :)

**Comment by zkreations** [comment]
The first works with a script that performs many queries (1 per tag). We are developing a version of our property and better, available in the next update.

**Comment by Warmuser** [comment]
Thanks, can I also ask you If would be possible to set a specific number of posts in the label search? Because I can only see a few of resoults, presumably generated from each date pubblication. Thanks anyway, your work is awesome! ;)

**Comment by zkreations** [comment]
it is necessary to add this "?max-results=8" at the end of the link, example:

https://www.zkreations.com/search/label/personal?max-results=8
